-- ["Gelendzhik"] = "Gelendzhik",
-- ["Krasnodar_Pashkovsky"] = "Krasnodar-Pashkovsky",
-- ["Sukhumi_Babushara"] = "Sukhumi-Babushara",
-- ["Gudauta"] = "Gudauta",
-- ["Batumi"] = "Batumi",
-- ["Senaki_Kolkhi"] = "Senaki-Kolkhi",
-- ["Kobuleti"] = "Kobuleti",
-- ["Kutaisi"] = "Kutaisi",
-- ["Tbilisi_Lochini"] = "Tbilisi-Lochini",
-- ["Soganlug"] = "Soganlug",
-- ["Vaziani"] = "Vaziani",
-- ["Anapa_Vityazevo"] = "Anapa-Vityazevo",
-- ["Krasnodar_Center"] = "Krasnodar-Center",
-- ["Novorossiysk"] = "Novorossiysk",
-- ["Krymsk"] = "Krymsk",
-- ["Maykop_Khanskaya"] = "Maykop-Khanskaya",
-- ["Sochi_Adler"] = "Sochi-Adler",
-- ["Mineralnye_Vody"] = "Mineralnye Vody",
-- ["Nalchik"] = "Nalchik",
-- ["Mozdok"] = "Mozdok",
-- ["Beslan"] = "Beslan",

A2AConfig = 
{
    {
        groupPrefix = "RedPlaneMilitaryFighterMig29s",
        spawnedGroupPrefix = "CapMig29S",
        minAltitude = 3000,
        maxAltitude = 6000,
        airBase = "Sukhumi-Babushara",
        isCap = true,
        isGci = false,
        grouping = 2,
        overhead = 1,
        airCraftLimit = 8,
        minFrontlineDistance = 40000,
        maxFrontlineDistance = 100000
    },
    {
        groupPrefix = "BlueF18CCap",
        spawnedGroupPrefix = "BlueCapF18C",
        minAltitude = 3000,
        maxAltitude = 6000,
        airBase = "Kutaisi",
        isCap = true,
        isGci = false,
        grouping = 2,
        overhead = 1,
        airCraftLimit = 8,
        minFrontlineDistance = 40000,
        maxFrontlineDistance = 100000 
    }
}